sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env python=$PYTHON_VERSION nose flake8
  - source activate test-env
  - conda install --yes -c bioconda VSEARCH==2.0.3 MAFFT==7.221 SortMeRNA==2.0 biom-format
  - conda install --yes -c biocore deblur=1.0.1
  - pip install https://github.com/qiime2/qiime2/archive/2017.2.0.zip https://github.com/qiime2/q2-types/archive/2017.2.0.zip https://github.com/qiime2/q2cli/archive/2017.2.0.zip https://github.com/qiime2/q2templates/archive/2017.2.0.zip
  - pip install .
  - git clone https://github.com/qiime2/q2lint
script:
  - nosetests
  - flake8 q2_deblur setup.py
  - python q2lint/q2lint.py
  - qiime deblur denoise-16S --i-demultiplexed-seqs q2_deblur/assets/demux.qza --o-table denoised.qza --o-representative-sequences reps.qza --o-stats stats.qza --p-trim-length 100
  - qiime deblur denoise-other --i-demultiplexed-seqs q2_deblur/assets/demux.qza --o-table denoised.qza --o-representative-sequences reps.qza --o-stats stats.qza --i-reference-seqs q2_deblur/assets/test_reference.qza --p-trim-length 100
